### ISSUE TITLE
View complete query

### ISSUE THREAD

**Issue by adc-jglick** [percona/qan-app#13]
I originally opened this because I didn't see the entire query listed anywhere.  I've since seen the queries in the "fingerprint" tab.  The example tab is empty however.

Is there a reason the example tab is empty?  It would be nice to see the query as soon as selecting it from the top 10 list.

**Comment by rnovikovP** [comment]
@adc-jglick query examples are now available in QAN. Please check https://pmmdemo.percona.com/qan2/profile/report/mysql?var-host=ps57r&queryID=88901A51719CB50B  for example
