### ISSUE TITLE
Query load percentages are wrong

### ISSUE THREAD

**Issue by zenramri** [percona/qan-app#20]
Looks like load percentages for individual queries are wrong.
In the example below, loads must be 94%, 2%, 2%, ... instead of 0.94%, 0.02%, 0.02%, ....

<img width="1411" alt="screen shot 2016-09-30 at 14 50 34" src="https://cloud.githubusercontent.com/assets/11166207/18993947/a529dd1c-871d-11e6-94c4-33ab6f47a972.png">

**Comment by askomorokhov** [comment]
Thanks for your feedback!

This will be fixed in v1.0.5.

**Comment by zenramri** [comment]
Thank you!
